backend/danswer/chat/process_message.py
backend/danswer/llm/answering/answer.py
backend/danswer/tools/built_in_tools.py
backend/danswer/tools/email/compose_email_tool.py
web/src/app/admin/assistants/AssistantEditor.tsx
web/src/app/assistants/ToolsDisplay.tsx
web/src/app/chat/modal/configuration/AssistantsTab.tsx

US#57859 : Added new plugin for Composing Email

US#57859 : Added new plugin for Composing Email

---

backend/danswer/tools/email/compose_email_tool.py
backend/danswer/tools/email/send_email.py

Sending email to the provided emails completed.

EmailService added

---

backend/danswer/tools/email/send_email.py

ComposeEmailTool - Subject removed from the email content

ComposeEmailTool - Subject removed from the email content

---

backend/danswer/tools/email/compose_email_tool.py
backend/danswer/tools/email/send_email.py

ComposeEmailTool - Logged in user id is taken as receiver email id

ComposeEmailTool - Logged in user id is taken as receiver email id

---

backend/danswer/server/settings/api.py
backend/danswer/server/settings/models.py
backend/danswer/server/settings/store.py
web/src/components/UserDropdown.tsx

Added new endpoints to do the CRUD operation for generic key value

Added new endpoints to do the CRUD operation for generic key value

---

backend/danswer/server/query_and_chat/chat_backend.py
backend/danswer/tools/email/send_email.py
web/src/app/chat/ChatPage.tsx

ComposeEmailPlugin- Added notification after sending email

ComposeEmailPlugin- Added notification after sending email

---

backend/danswer/server/manage/models.py
backend/danswer/server/manage/users.py

Endpoint: /manage/reset-password
Request Body: {"user_email": "<email>","new_password": "<new-pwd>" }

add reset-password api endpoint

---

backend/danswer/server/manage/models.py
backend/danswer/server/manage/users.py
backend/danswer/tools/email/send_email.py
backend/danswer/utils/password_generator.py
web/src/components/admin/users/SignedUpUserTable.tsx

Added the User Password Reset button in Admin Panel -> User Management

Feature/reset password UI

---

backend/danswer/tools/questions_recommender/recomend_questions_using_llm.py
backend/danswer/tools/text_to_sql/sql_generation_tool.py

response converted to JSON
added logging
cleaned up code

Infographics Recommend Questions for File changes

---

backend/danswer/server/settings/api.py
backend/danswer/server/settings/models.py
backend/danswer/server/settings/store.py
web/src/app/auth/login/EmailPasswordForm.tsx
web/src/lib/assistants/fetchAssitantIcons.ts

API changed to support Plugin grouping

API changed to support Plugin grouping

---

backend/danswer/server/settings/api.py
backend/danswer/server/settings/models.py

Plugin info api updated with more details

Plugin info api updated with more details

---

web/src/app/admin/assistants/AssistantEditor.tsx
web/src/app/admin/assistants/interfaces.ts
web/src/lib/assistants/fetchAssistantInfo.ts
web/src/lib/assistants/updateAssistantPreferences.ts

Plugin info related changes - In Edit plugin, current plugin info loaded and while updating plugin all the changes to the plugin info also gets saved

Plugin info related changes

---

backend/danswer/tools/email/send_email.py
web/src/app/chat/ChatPage.tsx
web/src/app/chat/message/Messages.tsx

Email Subject handled for Arabic language

Email Subject handled for Arabic language

---

web/src/app/chat/input/ChatInputOption.tsx
web/src/app/chat/message/Messages.tsx

Arabic responses supports rtl direction

Arabic responses supports rtl direction

---

backend/danswer/server/settings/api.py
backend/danswer/server/settings/store.py

Disabled cache for images

---

web/src/app/chat/ChatPage.tsx
web/src/app/chat/message/Messages.tsx

Email draft option enabled

---

backend/danswer/server/settings/api.py
web/src/app/auth/login/EmailPasswordForm.tsx
web/src/app/chat/ChatPage.tsx
web/src/components/Hoverable.tsx

Fixed issue of double click and username was not displayed correctly in certain scenario. Also removed few unused code

Release2 dev branch

---

deployment/docker_compose/docker-compose.dev.new.gpu.yml
web/src/app/admin/assistants/AssistantEditor.tsx
web/src/app/chat/ChatIntro.tsx
web/src/app/chat/ChatPage.tsx
web/src/app/chat/message/Messages.tsx
web/src/lib/assistants/fetchAssistantInfo.ts
web/src/lib/constants.ts

updated the icon volume reference 
moved default value to the constant file for better maintenance
Enable cache for assistant info

updated the icon volume reference 

---

backend/danswer/server/query_and_chat/chat_backend.py
backend/danswer/tools/built_in_tools.py
backend/danswer/tools/infographics/data_infographics_tool.py
backend/danswer/tools/infographics/generate_sql_for_dataframe.py
backend/danswer/tools/infographics/plot_summarize_generate_sql.py
backend/danswer/tools/infographics/resolve_plot_parameters_using_llm.py
backend/danswer/tools/questions_recommender/exceptions.py
backend/danswer/tools/questions_recommender/recomend_questions_using_llm.py
backend/danswer/tools/summary/split_by_sentence_tokens.py

1. Made main prompt dynamic
2. Recommendation prompt will be accepted as user input
3. Question recommendation for unstructured data like pdf, txt, docx

Infographics changes

---

web/src/app/admin/assistants/AssistantEditor.tsx
web/src/app/auth/login/page.tsx
web/src/app/chat/message/Messages.tsx

Fixed UI issues reported, Hide Create User, Hide Copy icon from response feedback of chat and increased the height of the System prompt

Fixed UI issues reported

---

web/src/app/chat/message/Messages.tsx
web/src/components/CopyButton.tsx

Enabled the copy button and fixed issue of copy to clipboard

Enabled the copy button and fixed issue of copy to clipboard

---

backend/danswer/server/query_and_chat/chat_backend.py
backend/danswer/tools/infographics/exceptions.py
backend/danswer/tools/infographics/plot_summarize_generate_sql.py
backend/danswer/tools/utils.py

1. Fix for comma separated data in column for questions recommendation service
2. Fix for loading excel (containing comma separated data in column) to dataframe

Infographics

---

backend/danswer/chat/load_yamls.py
backend/danswer/chat/personas.yaml
deployment/db_kit/plugins/Update_Persona.sql

Updated default plugin's is_public property

Updated default plugin's is_public property
